### ISSUE TITLE
陈老师你的仓库乱码了

### ISSUE THREAD

**Issue by Naville** [r0ysue/AndroidFridaSeniorBook#2]
https://github.com/r0ysue/AndroidFridaSeniorBook/blob/main/Chap10/æ%C2%A0·æ%C2%9C¬.apk
https://github.com/r0ysue/AndroidFridaSeniorBook/tree/main/Chap10/traceæ%C2%97¥å¿%C2%97

**Comment by r0ysue** [comment]
fixed
